# Copyright BigchainDB GmbH and BigchainDB contributors
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

---
- name: Building BigchainDB-all-in-one Docker
  docker_image:
    name: "{{ all_image_name }}"
    state: build
    tag: "{{all_image_tag }}"
    dockerfile: Dockerfile-all-in-one
    path: "{{ home_dir }}/bigchaindb/Dockerfile-all-in-one"
    nocache: yes
  when: stack_type|lower == "docker" or stack_type|lower == "cloud"
  tags: [bigchaindb-all-in-one]

- name: Configuring BigchainDB-all-in-one Containers
  docker_container:
    name: "all_config_gen"
    image: "{{ all_image_name }}:{{ all_image_tag }}"
    detach: true
    volumes:
      - "{{ tendermint_host_mount_config_dir }}{{ tendermint_home }}:{{ tendermint_home }}"
    entrypoint: ''
    command: |
      bash -c 'tendermint init &&
        jq ".validators=[]" /tendermint/config/genesis.json > /tendermint/config/genesis.tmp &&
        mv /tendermint/config/genesis.tmp /tendermint/config/genesis.json && rm /tendermint/config/node_key.json &&
        for i in $( seq {{ stack_size }} );do
        tendermint gen_validator > /tendermint/config/priv_validator$i.json;
        tendermint gen_node_key > /tendermint/config/node_id$i; mv /tendermint/config/node_key.json /tendermint/config/node_key$i.json;
        cat tendermint/config/priv_validator$i.json | jq ".pub_key" | jq ". as \$k | {pub_key: \$k, power: \"10\",
          name: \"{{ all_docker_name }}$i\"}" > pub_validator$i.json;
        cat /tendermint/config/genesis.json | jq ".validators |= .+ [$(cat pub_validator$i.json)]" > tmpgenesis;
        mv tmpgenesis /tendermint/config/genesis.json;
        done'
  when: stack_type|lower == "docker" or stack_type|lower == "cloud"
  tags: [bigchaindb-all-in-one]

- name: Starting BigchainDB-all-in-one Containers
  docker_container:
    name: "{{ all_docker_name }}{{ item }}"
    hostname: "{{ all_docker_name }}{{ item }}"
    image: "{{ all_image_name }}:{{ all_image_tag }}"
    detach: true
    network_mode: bridge
    networks:
      - name: "{{ bigchaindb_docker_net }}"
    published_ports:
      - "{{ bigchaindb_default_server_port }}"
      - "{{ bigchaindb_default_ws_port }}"
      - "{{ tendermint_abci_port }}"
      - "{{ tendermint_p2p_port }}"
      - "{{ tendermint_rpc_port }}"
      - "{{ mongodb_port }}"
      - "{{ mongodb_admin_port }}"
    volumes:
      - "{{ mongodb_host_mount_dir }}{{ item|string }}/db:{{ mongodb_storage_path }}"
      - "{{ mongodb_host_mount_dir }}{{ item|string }}/configdb:{{ mongodb_config_path }}"
      - "{{ tendermint_host_mount_dir }}{{ item|string }}{{ tendermint_home }}:{{ tendermint_home }}"
      - "{{ tendermint_host_mount_config_dir }}{{ tendermint_home }}:/tendermint_config"
    entrypoint: ''
    command: bash -c 'mongod && cp /tendermint_config/genesis.json /tendermint/config/genesis.json &&
      mv /tendermint_config/priv_validator"{{ item|string }}".json /tendermint/config/priv_validator.json &&
      mv /tendermint_config/node_key"{{ item|string }}".json /tendermint/config/node_key.json &&
      peers=() && for i in $( seq {{ stack_size }} );do peers+=($(cat /tendermint_config/node_id$i)@"{{ all_docker_name }}$i:{{ tendermint_p2p_port }}");done &&
      peers=$(IFS=","; echo "${peers[*]}") && echo $peers &&
      tendermint node --p2p.persistent_peers="$peers" --p2p.laddr "tcp://"{{ all_docker_name }}{{ item|string }}":26656"
      --proxy_app="tcp://"{{ all_docker_name }}{{ item|string }}":26658" --consensus.create_empty_blocks=false --p2p.pex=false && bigchaindb -l DEBUG start'
    state: started
    keep_volumes: true
  with_sequence: start=1 end="{{ stack_size|int }}" stride=1
  when: stack_type|lower == "docker" or stack_type|lower == "cloud"
  tags: [bigchaindb-all-in-one]

